spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pedidos360}
    username: ${DB_USERNAME:pedidos360}
    password: ${DB_PASSWORD:pedidos360}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
app:
  security:
    cognito:
      issuer: ${COGNITO_ISSUER:https://cognito-idp.us-east-1.amazonaws.com/local-placeholder}
      client-id: ${COGNITO_CLIENT_ID:local-client}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
